### ISSUE TITLE
Add "Average number nodes per branch level" 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/cassava#15]
Requested by @rachealmukisa for the flowering experiment:

Average number nodes per branch level description:
counting all nodes per branch each level (if on a plant at harvest on each level (if more then 1 branch, select one branch and count nodes up  to the apical shoot), value averaged per plot.
see as well: https://github.com/solgenomics/sgn/issues/950

**Comment by nmenda** [comment]
new term CO_334:0000343

commit will follow soon

**Comment by nmenda** [comment]
https://github.com/solgenomics/cassava/commit/58bfd0763a98dfcf9887940e753557592b400534

**Comment by rachealmukisa** [comment]
The 'average number of nodes' is required at branching levels 1,2,3 and 4.

**Comment by nmenda** [comment]
https://github.com/solgenomics/cassava/commit/4421287b2a77c464f910e99e9086274d05f2f1d9
