### ISSUE TITLE
Add "number of pollinated flowers"

### ISSUE THREAD

**Issue by rachealmukisa** [solgenomics/cassava#16]
Currently , in the database, we have "CO:0000143 female flower number counting" which is A count of the number female flowers after the buds appear, mature, and grow in size to become distinctive at the first, second, and third branch levels.  

For pollination, we need to include the "total number of flowers pollinated per plot" in the new description for ontology "number of pollinated flowers"

For references see https://github.com/solgenomics/sgn/issues/950

**Comment by nmenda** [comment]
need to follow up on existing traits and check if the definition needs tweaking 
@aafolabi
