### ISSUE TITLE
Add a new ontology term for "Number of female flowers at different branching levels"

### ISSUE THREAD

**Issue by rachealmukisa** [solgenomics/cassava#18]
We need to add a new ontology term for "Number of female flowers at different branching levels". What is existing on cassavabase is the "Female Flower Number conting" but not at different levels of branching

**Comment by nmenda** [comment]
added the terms https://github.com/solgenomics/cassava/pull/19/commits/fe23542f88aa34266755ae1d1fb84b94855c3f4e
commit under review by @aafolabi
