### ISSUE TITLE
Flowering traits at specific branching levels 

### ISSUE THREAD

**Issue by aafolabi** [solgenomics/cassava#22]
More traits related to flowering experiment measured at different branching levels: Days to forking event (first , second and third), Date of abortion on different tiers, Days to senescence, Number of branches, Number of inflorescence, Number of flower buds, Number of male flower, Days to fruitset, Number of fruit.

**Comment by bauchetg** [comment]
Hello @aafolabi 
-Number of fruit is already there I think:
CO:0000156 number of fruits counting 
-Number of flower buds:
Flowers are there but no buds, what should be the relationship between the two terms?
-Number of male flowers:
CO:0000144 male flower number counting 
CO:0000274 male flower number counting on all levels 
- Number of inflorescence:
Maybe synonym? CO:0000420 Number of terminal branches with inflorescence

**Comment by aafolabi** [comment]
Hi @bauchetg

The variable terms added are branching level specific terms. The descriptions we have described earlier is either on all branching level or per plot. 
CO:0000156 number of fruits counting : It is the totality of all fruits in all branching levels.  

Number of flower buds: The flower buds is neither female nor male. There is the inability to distinguish between the two. This is also counted at different branching levels. Count of female and male is different.

CO:0000144 male flower number counting : Protocol is for tier 1, 2 and 3. No more no less.
 CO:0000274 male flower number counting on all levels : Male flower count on all the levels available

What has been added is the term for specific count at different level of branching.

•Number of inflorescence:
 Maybe synonym? CO:0000420 Number of terminal branches with inflorescence: The interest here is on the count of the terminal branches.

**Comment by bauchetg** [comment]
@aafolabi @titima15 ,regarding the crossing data upload some additions may be necessary:

no of flowers pollinated (= new trait)
Total no of flowers pollinated (= new trait)
no of fruit set (= already listed)

bags (= maybe be stored in seed lot object  as/Seedlot )
no of seed (= nmaybe be stored in seed lot object  as /Seed lot value)

**Comment by bauchetg** [comment]
@naama @aafolabi : just saw your commits for previous traits, I created a new issue for the new ones see #24
