### ISSUE TITLE
agronomic traits at plant level

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/cassava#4]
CASS needs 4 agronomic traits at the plant level:
fresh root weight
fresh shoot weight
fresh total weight
harvest index

Originally posted ticket here: https://github.com/solgenomics/cassbase/issues/3

**Comment by nmenda** [comment]
> Harvest index is okay: https://www.cassavabase.org/cvterm/70668/view
> Fresh root weight should not say plot in the definition: https://www.cassavabase.org/cvterm/70666/view
> Fresh shoot weight should not say plot in the def: https://www.cassavabase.org/cvterm/70773/view
> I can't find 'fresh total weight' so it may need to be added.
>

**Comment by nmenda** [comment]
add new terms for measuring by plant, make the old term name ' ... by plot' 
and make both terms children of one common parent , e.g . 'Fresh root weight' 
child term 1 : 'fresh root weight by plot'
child term 2: 'fresh root weight by plant'

**Comment by nmenda** [comment]
fresh root weight per plant : CO:0000304
fresh shoot weight per plant: CO:0000307

fresh total weight : is this the sum of root weight + shoot weight?

**Comment by aafolabi** [comment]
I think we need clarification on total weight

On Dec 22, 2016 10:26 PM, Naama Menda <notifications@github.com> wrote:

fresh root weight per plant : CO:0000304
fresh shoot weight per plant: CO:0000307

fresh total weight : is this the sum of root weight + shoot weight?

**Comment by nickmorales** [comment]
Thanks! Yes fresh total weight is just root weight + shoot weight and they are interested in recording this measurement. Please let me know what the term id will be.

**Comment by nmenda** [comment]
@nickmorales this sounds like a derived trait. If they measure the root weight and the shoot weight, then it's easy to calculate the total weight, and maybe we don't need a new term for it
what do you think?

**Comment by nmenda** [comment]
https://github.com/solgenomics/cassava/commit/39c2606bd04214f819f170f5e8edf7f8a260bdf9#diff-38329a0c2a633e3f02f646e8cbd72924R2954
