### ISSUE TITLE
Additional traits for CASS

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/cassava#5]
Andreas Gisel needs these terms in the ontology because he has already collected data using these terms.

- Stick length (cm)
- Number internodes on stick
- Number internodes with roots
- Number fibrous roots on stick
- Number storage roots on stick
- Number roots at end of the stick

He has been in contact with Crop Ontology, but the terms have not been added yet.

Laure David at ETH needs these terms in the ontology because she has already collected data:

These 4 can be added under a new category called Starch Properties under the existing Quality Trait category:
- Starch granule morphology (pictures)
- Starch granule average diameter (µm)
- Starch granule size distribution with three categories. 1: between 0-7µm ; 2: 8-14 µm ; 3 : 15 - 22 µm.
- Chain length distribution : for each sample I have 80 values : dp3 to dp82

The existing 'starch content percentage' term uses a different definition than what she is doing, so we may need to add a new 'starch content' term

**Comment by nmenda** [comment]
can they provide definitions for each term, what they are measuring , how , and what unit?

**Comment by nickmorales** [comment]
- Stick length (cm) - Length of the planting stick at the sampling time point
- Number internodes on stick - Number of the internodes of the planting stick
- Number internodes with roots - Number of the internodes which developed fibrous or storage roots
- Number fibrous roots on stick - Total number of fibrous roots emerging from the planting stick
- Number storage roots on stick  - Total number of storage roots emerging from the planting stick
- Number roots at end of the stick - Total number of roots (fibrous and storage) which emerged from the cutting side at the end of the stick

**Comment by aafolabi** [comment]
Planting stick means plantable stem. It has an estimated length of about 20cm. Am assuming they are measuring each length of the stem before planting...we can confirm!!!
Number internodes on stick - I think the method of measurement is missing. Internode should be the distance between nodes on a stem. So is this a paired nodes counting ?

The timing and a detailed method of measurement should be provided for the following:

•Number internodes with roots - Number of the internodes which developed fibrous or storage roots
•Number fibrous roots on stick - Total number of fibrous roots emerging from the planting stick
•Number storage roots on stick - Total number of storage roots emerging from the planting stick
•Number roots at end of the stick - Total number of roots (fibrous and storage) which emerged from the cutting side at the end of the stick.

**Comment by nickmorales** [comment]
The starch content term method is "Starch is extracted with perchloric acid method and quantify with enzymatic assay" and unit is %DW

@nickmorales : is this different from the 'starch content percentage' we have in CO? CO_334:0000071

**Comment by nickmorales** [comment]
Andreas says that the measurements are taken at many different time points (e.g. 4 weeks after planting, up to 52 weeks after planting). He says they just pull the plant and take the measurements on the planting stick.

In CASS we are combining the CO with a "Time Ontology" to take care of the different time points; therefore, the CO terms need to be time independent.

@nmenda @aafolabi please assign identifiers to these terms as soon as possible.

**Comment by nmenda** [comment]
so should those be traits, not variables, since those will be used for post-composing with 'time ontology'  ?

**Comment by nickmorales** [comment]
@aafolabi @nmenda i suppose so. if we could create placeholder identifiers for now that would work for me as well, that way the people at CO can figure out how to fully integrate these terms into the ontology.

**Comment by nmenda** [comment]
@nickmorales 
here are the terms for the 'planting stick' traits 
82ffca52f492b3c1105d994dee8af5f7a4e1a4d0

**Comment by nmenda** [comment]
terms for starch related variables 
67e00e6216f2e5b0fe0c4dae07bc9f14b02ce009
