### ISSUE TITLE
Differentiation between storage root weight and fibrous root weight

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/cassava#8]
From Andreas:

With CO I cannot differentiate between fibrous and storage roots.

I guess we would need under "fresh root weight per plant|CO:0000304” a differentiation the following:

- fresh storage root weight per plant
- fresh fibrous root weight per plant

**Comment by aafolabi** [comment]
@nmenda and @nickmorales fibrous root is a developmental stage in root formation. Fibrous root  bulk, accumulate starch and enlarge to form storage root. I think this assessment is done at an earlier stage after planting. We can confirm if this is what Andreas team does actually...then the ontology can be updated.

**Comment by nmenda** [comment]
@aafolabi @nickmorales did you contact Andreas to clarify this ?

**Comment by nickmorales** [comment]
From Andreas:

Fibrous roots do not turn into storage roots.

"from the planting stick two types of roots emerge: the fibrous roots and a
sort of pre-storage roots which eventually bulk and become storage roots or
stay in the pre-storage root state taking probably over other functions.


 see:
Anatomical Assessment of Root Formation and Tuberization in Cassava
(Manihot esculenta Crantz)
Yeetoh Chaweewan & Nigel Taylor
Tropical Plant Biol. (2015) 8:1–8
DOI 10.1007/s12042-014-9145-5

"

**Comment by nickmorales** [comment]
@aafolabi @nmenda Please see the above comment

**Comment by nickmorales** [comment]
@aafolabi @nmenda Should I assign placeholders in cassbase?

**Comment by nickmorales** [comment]
@aafolabi @nmenda Any news on this issue?

**Comment by nickmorales** [comment]
30875f382777b08f4ad46a53b6e222ef7860132e
